name: jalmaani
favicon: null
layout_spectrum: 0.6584632056765258
typography_spectrum: 0.20380717958323658
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6300198577810079
  lightness: 0.044109473237767816
  saturation: 0.25847247475758195
  rhythmicContrast: 0.20150030427612364
purpose: []
